version: '3'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - slva:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app-author:
    image: crisb22023/app-author:v1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-author.rule=Host(`app-author`)"
      - "traefik.http.routers.app-author.entrypoints=web"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/distribuida
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "9099"

  app-book:
    image: crisb22023/app-book:v1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-book.rule=Host(`app-book`)"
      - "traefik.http.routers.app-book.entrypoints=web"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8080"

  traefik:
    image: "traefik:v3.0"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:9090" # entrypoint on docker e.g: 8888
    ports:
      - "9090:9090" # localhost : entrypoint on docker e.g:  4545:8888
      - "6099:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
volumes:
  slva: